<a href="https://colab.research.google.com/github/Anoop96/Classification_Algo_sklearn_toy_datsets/blob/master/UCI_Breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


# Dataset

In [2]:
data = pd.read_csv('Data.csv')
print(data.head())

   Sample code number  Clump Thickness  ...  Mitoses  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]


In [3]:
data.shape

(683, 11)

In [4]:
# check for missing values
data.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [6]:
# types of dependent variables
data.Class.value_counts()

2    444
4    239
Name: Class, dtype: int64

# Split the data into train and test set

In [0]:
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25 , random_state=0)

# Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

# Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
cl = LogisticRegression()
cl.fit(x_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

### Make the confusion Matrix

In [17]:
y_pred = cl.predict(x_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[103   4]
 [  5  59]]
0.9473684210526315


# KNN classifier

In [18]:
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
cl.fit(x_train_scaled,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

### Confusion matrix

In [19]:
y_pred = cl.predict(x_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[103   4]
 [  5  59]]
0.9473684210526315


# Naive Bayes Classifier

In [20]:
from sklearn.naive_bayes import GaussianNB
cl = GaussianNB()
cl.fit(x_train_scaled,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

### Confusion Matrix

In [21]:
y_pred = cl.predict(x_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[99  8]
 [ 2 62]]
0.9415204678362573


# Decision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier
cl = DecisionTreeClassifier(criterion='entropy',random_state=0)
cl.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

### Confusion Matrix

In [24]:
y_pred = cl.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[104   3]
 [  4  60]]
0.9590643274853801


# Random Forest Classifier

In [35]:
from sklearn.ensemble import RandomForestClassifier
cl = RandomForestClassifier(n_estimators=15,criterion='entropy',random_state=0)
cl.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=15,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

### Confusion Matrix

In [36]:
y_pred = cl.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[104   3]
 [  4  60]]
0.9590643274853801


# Linear SVM

In [37]:
from sklearn.svm import SVC
cl = SVC(kernel='linear',random_state=0)
cl.fit(x_train_scaled,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

### Confusion Matrix

In [38]:
y_pred = cl.predict(x_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[102   5]
 [  5  59]]
0.9415204678362573


# Non linear SVM 

In [39]:
from sklearn.svm import SVC
cl = SVC(kernel='rbf',random_state=0)
cl.fit(x_train_scaled,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

### Confusion Matrix

In [40]:
y_pred = cl.predict(x_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[101   6]
 [  3  61]]
0.9473684210526315
